name: cache actions
description: GET THE dependencies and store them
inputs:
  caching:
    description: whether to cache dependencies or not
    required: false
    default: "true"
outputs:
  used-cache:
    description: whether the cached was used or not
    value: ${{steps.install.outputs.cacheecho}}
runs:
  using: composite
  steps:
    - name: Cache dependencies

      if: inputs.caching=='true'

      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'

      run: |
        npm ci
        echo "cacheecho=${{inputs.caching}}">>$GITHUB_OUTPUT
      shell: bash
